# Site settings
title: Agile & Java
email: bitard.michael@gmail.com
description: "Another blog on agile and java. Maybe i'll add kittens and food recipe if my partner helps me."
baseurl: ""
url: "http://agileek.github.io"
twitter_username: BitardMichael
github_username:  MichaelBitard

# Build settings
markdown: kramdown
permalink: pretty
