theme = 'PaperMod'
baseURL = "https://agileek.github.io"
disablePathToLower = true
languageCode = "en-us"
title = "Software"
enableRobotsTXT = true
sectionPagesMenu = 'main'
summaryLength = 0

[pagination]
pagerSize = 200

[outputs]
home = ["HTML", "RSS", "JSON", "GEMINI", "GEMINI_RSS"]
page = ["HTML", "GEMINI"]

[params]
env = "production"
description = "Yet another blog on software stuff"
author = "Michaël Bitard"

defaultTheme = "auto"
# disableThemeToggle: true
ShowShareButtons = true
ShowReadingTime = true
disableSpecial1stPost = true
displayFullLangName = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
comments = false
images = ["images/home.png"]
hideAuthor = true
# homeInfoParams.Title="PaperMod's Demo"
# homeInfoParams.Content="👋 Welcome to demo page of Hugo's theme PaperMod!"
[params.editPost]
URL = "https://github.com/agileek/agileek.github.io/tree/develop"
Text = "Suggest Changes"                                          # edit text
appendFilePath = true                                             # to append file path to Edit link
[params.footer]
text = "Yet another blog on software stuff"

[markup.goldmark.renderer]
unsafe = true

# FIXME add asciinema
# FIXME Languages
# [[module.imports]]
#     path= "https://github.com/hybras/hugo-asciinema"
[mediaTypes]
[mediaTypes.'text/gemini']
delimiter = '.'
suffixes = ['gmi']

[outputFormats]
[outputFormats.GEMINI]
baseName = 'index'
isHTML = false
isPlainText = false
mediaType = 'text/gemini'
protocol = "gemini://"
permalinkable = true

[outputFormats.GEMINI_RSS]
baseName = 'feed'
isPlainText = false
mediaType = 'application/rss+xml'
protocol = "gemini://"
