name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - develop

concurrency:
    group: environment-${{ github.ref }}
    cancel-in-progress: true
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
